### ISSUE TITLE
Possible to have more than 1 login page for redirect when not authenticated?

### ISSUE THREAD

**Issue by schleppy** [bigpresh/Dancer-Plugin-Auth-Extensible#52]
I have a login page `/login` that has been around a long time.  

Now I have a new login page that is for a specific section of the site and as such I would like users trying to access that section who are not authorized to be redirected to a different login page (say `/some_section/login`).

I think I can do this all manually by checking for logged in status, then checking roles and redirecting myself, but was wondering if there is another way so I could still use syntax like

``` perl
get '/some-section/:page' => require_any_role [qw(User Admin Other)] => sub {
```

**Comment by bigpresh** [comment]
(Wow, slow reply here... sorry!)

No, there's no such ability built-in - you'd need to do that yourself, as you described.

I'm not sure of a clean way this could be implemented, nor how common a requirement it would be, so I think I'm going to consider this an unlikely feature to add - I'm willing to be persuaded otherwise, though.

As a slight hack, maybe the login page could look at the route they were trying to access, and select the template to use accordingly - if the URL it ends up at doesn't matter, and it's just the look/content that matters?
